services:

  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile.jupyter
    environment:
      DOCKER_STACKS_JUPYTER_CMD: notebook
    volumes:
      - ./scraping:/home/jovyan/scriping
    ports:
      - 8888:8888
    command: "start-notebook.sh --ServerApp.root_dir=/home/jovyan/scriping --NotebookApp.token="

  gui:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 7860:7860
    volumes:
      - ./app/main.py:/usr/src/app/main.py:ro
      - ./app/main_page_image.jpg:/usr/src/app/main_page_image.jpg:ro
      - ./scraping/model.pkl:/usr/src/app/model.pkl:ro
    command: "python3 main.py"

version: "3.3"
