FROM python:3.10-slim
# FROM cr.bank-hlynov.ru/docker/python:3.10.11-bullseye

WORKDIR /usr/src/app

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && \
    pip install gradio

EXPOSE 7860
ENV GRADIO_SERVER_NAME="0.0.0.0"
CMD ["python", "main.py"]
